name: Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://templates/zresources.yaml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name my-ha-vpc-stack \
            --template-file templates/zresources.yaml \
            --parameter-overrides $(cat parameters/myparams.json | jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"') \
            --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
